### ISSUE TITLE
naf_pendulum.py example fails when building model

### ISSUE THREAD

**Issue by eklitzke** [matthiasplappert/keras-rl#102]
I'm using master, and I get this error when trying to run `examples/naf_pendulum.py`:

```
Traceback (most recent call last):
  File "examples/naf_pendulum.py", line 66, in <module>
    x = Dense(((nb_actions * nb_actions + nb_actions) / 2))(x)
  File "/home/evan/code/keras-rl/.venv/lib/python3.6/site-packages/keras/engine/topology.py", line 551, in __call__
    self.build(input_shapes[0])
  File "/home/evan/code/keras-rl/.venv/lib/python3.6/site-packages/keras/layers/core.py", line 827, in build
    constraint=self.kernel_constraint)
  File "/home/evan/code/keras-rl/.venv/lib/python3.6/site-packages/keras/engine/topology.py", line 384, in add_weight
    weight = K.variable(initializer(shape), dtype=K.floatx(), name=name)
  File "/home/evan/code/keras-rl/.venv/lib/python3.6/site-packages/keras/initializers.py", line 208, in __call__
    dtype=dtype, seed=self.seed)
  File "/home/evan/code/keras-rl/.venv/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 3177, in random_uniform
    dtype=dtype, seed=seed)
  File "/home/evan/code/keras-rl/.venv/lib/python3.6/site-packages/tensorflow/python/ops/random_ops.py", line 244, in random_uniform
    seed2=seed2)
  File "/home/evan/code/keras-rl/.venv/lib/python3.6/site-packages/tensorflow/python/ops/gen_random_ops.py", line 220, in _random_uniform
    seed=seed, seed2=seed2, name=name)
  File "/home/evan/code/keras-rl/.venv/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 585, in apply_op
    param_name=input_name)
  File "/home/evan/code/keras-rl/.venv/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 61, in _SatisfiesTypeConstraint
    ", ".join(dtypes.as_dtype(x).name for x in allowed_list)))
TypeError: Value passed to parameter 'shape' has DataType float32 not in list of allowed values: int32, int64
```

**Comment by matthiasplappert** [comment]
Which version of tensorflow are you using (`pip freeze | grep "tensorflow"`)?

**Comment by pollini** [comment]
Unfortunately, this is still an issue (using anaconda/python 3.5, tensorflow 1.3.0, and latest keras-rl 0.3.1). The problem lies in line 66 of `examples/naf_pendulum.py`:
With `x = Dense(((nb_actions * nb_actions + nb_actions) / 2))(x)` we are trying to pass a float into the `Dense()` function. I was able to solve this by casting the term `(nb_actions * nb_actions + nb_actions) / 2` to an int, which, in order to successfully execute the example, yields for line 66:
`x = Dense(int(((nb_actions * nb_actions + nb_actions) / 2)))(x)`

Though I do not know for sure if this is an error in the code or if I am doing something wrong, and if this workaround will hold for other values of the `nb_actions` variable?

**Comment by matthiasplappert** [comment]
Ah yes, good catch! This is because I originally wrote this for Python 2.7, which handles divisions differently than Python 3.x. The right thing to do here is to replace `/` with `//`, which is the correct integer division. I'll fix that right now.

**Comment by matthiasplappert** [comment]
Addressed in https://github.com/matthiasplappert/keras-rl/commit/d9b72f3881f8d2b286d77b31c4e7f12c7d7aa4d4
