### ISSUE TITLE
keras-rl seems to require a specific version of supporting packages

### ISSUE THREAD

**Issue by parunach** [matthiasplappert/keras-rl#130]
I installed the latest keras-rl and have all packages updated. When I try

`from rl.agents.dqn import DQNAgent`

I get the error message

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/lib/python2.7/site-packages/rl/agents/__init__.py", line 2, in <module>
>     from .dqn import DQNAgent, ContinuousDQNAgent
>   File "/usr/lib/python2.7/site-packages/rl/agents/dqn.py", line 4, in <module>
>     import keras.backend as K
>   File "/usr/lib64/python2.7/site-packages/keras/__init__.py", line 4, in <module>
>     from . import activations
>   File "/usr/lib64/python2.7/site-packages/keras/activations.py", line 6, in <module>
>     from .engine import Layer
>   File "/usr/lib64/python2.7/site-packages/keras/engine/__init__.py", line 8, in <module>
>     from .training import Model
>   File "/usr/lib64/python2.7/site-packages/keras/engine/training.py", line 25, in <module>
>     from .. import callbacks as cbks
>   File "/usr/lib64/python2.7/site-packages/keras/callbacks.py", line 26, in <module>
>     from tensorflow.contrib.tensorboard.plugins import projector
>   File "/usr/lib/python2.7/site-packages/tensorflow/contrib/__init__.py", line 31, in <module>
>     from tensorflow.contrib import factorization
>   File "/usr/lib/python2.7/site-packages/tensorflow/contrib/factorization/__init__.py", line 24, in <module>
>     from tensorflow.contrib.factorization.python.ops.gmm import *
>   File "/usr/lib/python2.7/site-packages/tensorflow/contrib/factorization/python/ops/gmm.py", line 27, in <module>
>     from tensorflow.contrib.learn.python.learn.estimators import estimator
>   File "/usr/lib/python2.7/site-packages/tensorflow/contrib/learn/__init__.py", line 88, in <module>
>     from tensorflow.contrib.learn.python.learn import *
>   File "/usr/lib/python2.7/site-packages/tensorflow/contrib/learn/python/__init__.py", line 23, in <module>
>     from tensorflow.contrib.learn.python.learn import *
>   File "/usr/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/__init__.py", line 25, in <module>
>     from tensorflow.contrib.learn.python.learn import estimators
>   File "/usr/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/__init__.py", line 297, in <module>
>     from tensorflow.contrib.learn.python.learn.estimators.dnn import DNNClassifier
>   File "/usr/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/dnn.py", line 30, in <module>
>     from tensorflow.contrib.learn.python.learn.estimators import dnn_linear_combined
>   File "/usr/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/dnn_linear_combined.py", line 31, in <module>
>     from tensorflow.contrib.learn.python.learn.estimators import estimator
>   File "/usr/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 49, in <module>
>     from tensorflow.contrib.learn.python.learn.learn_io import data_feeder
>   File "/usr/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/learn_io/__init__.py", line 21, in <module>
>     from tensorflow.contrib.learn.python.learn.learn_io.dask_io import extract_dask_data
>   File "/usr/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/learn_io/dask_io.py", line 26, in <module>
>     import dask.dataframe as dd
>   File "/usr/lib/python2.7/site-packages/dask/dataframe/__init__.py", line 3, in <module>
>     from .core import (DataFrame, Series, Index, _Frame, map_partitions,
>   File "/usr/lib/python2.7/site-packages/dask/dataframe/core.py", line 40, in <module>
>     pd.computation.expressions.set_use_numexpr(False)
> AttributeError: 'module' object has no attribute 'computation'

I see from the web that it is solved with a specific version of pandas. The latest version is 0.20.3.

**Comment by parunach** [comment]
Sorry, found that updating dask fixes this.
